apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-brain
  namespace: octopus-ocean
spec:
  replicas: 2
  selector:
    matchLabels:
      app: octopus-brain
  template:
    metadata:
      labels:
        app: octopus-brain
    spec:
      containers:
      - name: brain
        image: octopus/brain:latest
        ports:
        - containerPort: 8080
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: octopus-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: octopus-brain-service
  namespace: octopus-ocean
spec:
  selector:
    app: octopus-brain
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
